version: "3"
services:
  influx:
    image: influxdb:latest
    container_name: influx
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: ssdaa
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
    volumes:
      - ./data:/var/lib/influxdb2
    ports:
      - "8086:8086"
