services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    security_opt:
      - seccomp:unconfined
    runtime: nvidia
    restart: unless-stopped
    environment:
      - PLEX_CLAIM=xxxxxxxxxxxxxxxxxxxx
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: host
    volumes:
      - ./database:/config
      - ./transcode:/transcode
      - /mdata/data/media:/data

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Allocate all available GPUs to the container
              capabilities: [gpu]
