services:
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./conf/:/etc/prometheus/
        - ./data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      restart: always

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    links:
      - "prometheus:prometheus"
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'

volumes:
  grafana_storage: {}

# set connection in grafana »» http://prometheus:9090
# import dashboard from https://grafana.com/grafana/dashboards/

