services:
  timemachine:
    networks:
      tmmacvlan:
        ipv4_address: 192.168.1.5
    environment:
      - CUSTOM_AFP_CONF=false
      - LOG_LEVEL=info
      - MIMIC_MODEL=TimeCapsule6,106
      - TM_USERNAME=vg
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=SrvTimeMachine
      - VOLUME_SIZE_LIMIT=1200000000000
    restart: unless-stopped
    ports:
      - "548:548"
      - "636:636"
    volumes:
      - /mdata/data/backup/__time_machine:/opt/timemachine
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:latest
    hostname: timebck

networks:
  tmmacvlan:
    driver: macvlan
    driver_opts:
      parent: enp5s0f1
    ipam:
      config:
        - subnet: 192.168.1.0/24
    