{
 "title": "JVM",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": "show tag values where key = \"application\""
   },
   {
    "name": "instance",
    "query": "show tag values where key = \"instance\""
   },
   {
    "name": "server_uri",
    "query": "show tag values from http_server_requests with  key = \"uri\""
   },
   {
    "name": "client_uri",
    "query": "show tag values from http_client_requests with  key = \"uri\""
   }
  ]
 },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "mvc mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(mean) FROM \"http_server_requests\" WHERE (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/ AND \"uri\"=~/^$server_uri$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" }
     ]
    },
    {
     "alias": "mvc max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(upper) FROM \"http_server_requests\" WHERE (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/ AND \"uri\"=~/^$server_uri$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT max(\"count\") FROM \"http_server_requests\" WHERE (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/) AND (\"outcome\" != 'SUCCESS' or \"exception\" != 'None') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "outcome", "operator": "!=", "value": "SUCCESS" },
      { "condition": "AND", "key": "exception", "operator": "!=", "value": "None" }
     ]
    }
   ]
  },
  {
   "title": "URIs and latencies",
   "type": "table",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_server_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_server_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.5" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_server_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "p95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.95" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_server_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "0.99" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_server_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$server_uri$/" },
      { "condition": "AND", "key": "phi", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "mean duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(mean) FROM \"http_client_requests\" WHERE (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/ and \"uri\"=~/^$client_uri$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "max duration",
     "query": "SELECT mean(upper) FROM \"http_client_requests\" WHERE (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/ and \"uri\"=~/^$client_uri$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Upstream Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_client_requests",
     "query": "select max(count) from http_client_requests where (outcome!='SUCCESS' ) and (\"application\" =~ /^$application$/ AND \"instance\" =~ /^$instance$/ AND \"uri\"=~/^$client_uri$/) and $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "outcome", "operator": "!=", "value": "SUCCESS" }
     ]
    }
   ]
  },
  {
   "title": "Upstream URIs and latencies",
   "type": "table",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "uri" ], "type": "tag" }
     ],
     "measurement": "http_client_requests_percentile",
     "query": "select mean(value) from http_server_requests_percentile group by phi, uri",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tomcat_connections_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 81 },
   "targets": [
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_busy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Datasource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections_idle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hikaricp_connections_active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "[[measurement]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "G1 Old Gen" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "G1 Survivor Space" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "G1 Eden Space" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM nonheap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CodeHeap 'non-nmethods'" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" },
      {
       "condition": "AND",
       "key": "id",
       "operator": "=",
       "value": "CodeHeap 'non-profiled nmethods'"
      },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CodeHeap 'profiled nmethods'" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed Class Space" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistic": "Average",
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}