version: "3.2"
services:
  ubuntu-tool:
    image: ubuntu-tool
    build: .
    container_name: ubuntu-tool
    ports:
        - 4040:4040
    volumes:
        - ./data/:/mnt
    command: /bin/bash
    stdin_open: true
    tty: true
