services:
    ibmmq:
        image: ibmcom/mq:latest
        container_name: ibmmq
        ports:
            - "1414:1414"
            - "9157:9157"
            - "9443:9443"
        environment:
            - LICENSE=accept
            - MQ_APP_PASSWORD=xxxxxxxxxxx
            - MQ_ADMIN_PASSWORD=xxxxxxxxxxx
            - MQ_QMGR_NAME=QM1
            - MQ_ENABLE_METRICS=true
        volumes:
            - qm1data:/mnt/mqm
            
volumes:
  qm1data:
