version: "3"

services:
    ibmmq:
        image: ibmcom/mq:latest
        container_name: ibmmq
        ports:
            - "1414:1414"
            - "9157:9157"
            - "9443:9443"
        environment:
            - LICENSE=accept
            - MQ_APP_PASSWORD=passw0rd            
        volumes:
            - qm1data:/mnt/mqm
            
volumes:
  qm1data:


# visit console -> https://localhost:9443/ibmmq/console/login.html
# admin/passw0rd

