output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  api_key: "bk6hCZcB85nFC2nQrjoP:MUXR-ZTyoGt7iMYewnbNYA"

metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - memory
    - network
    - filesystem
    - process


metricbeat.config.modules:
  # Reload metricbeat modules every 10 seconds (optional)
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 7
  permissions: 0644

  